<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>FanDemo</RootNamespace>
    <AssemblyName>FanDemo</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\Settings.Designer.cs" />
    <Compile Remove="FanDemo.Tests\**\*.cs" />
    <Compile Remove="FanDemo.UITests\**\*.cs" />
    <Content Include="Images\*.jpg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
