name: Build WPF App

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.8.x  # Replace with the desired version

    - name: Build WPF App
      run: msbuild FanDemo.sln /p:Configuration=Release  # Update with your solution path

    # You can add more steps here, such as running tests or publishing artifacts
