name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8.x'  # Use the latest supported version for .NET 4.8 projects

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-build
