name: Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'  # Use the latest supported version for .NET 3.5 projects

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-build
